# Generated by Django 5.2.3 on 2025-06-15 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_auteurs', '0001_initial'),
        ('gestion_categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jeu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('annee_sortie', models.PositiveIntegerField()),
                ('photo_boite', models.ImageField(blank=True, upload_to='jeux/')),
                ('editeur', models.CharField(max_length=100)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_auteurs.auteur')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_categories.categorie')),
            ],
        ),
    ]
