# Generated by Django 5.2.3 on 2025-06-15 11:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_jeux', '0001_initial'),
        ('gestion_joueurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.PositiveSmallIntegerField()),
                ('commentaire', models.TextField(blank=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('jeu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_jeux.jeu')),
                ('joueur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_joueurs.joueur')),
            ],
        ),
    ]
